version: "3.6"

services:
  redis1:
    image: redis
    ports:
      - "4001:6379"
    restart: always
  redis2:
    image: redis
    ports:
      - "5001:6379"
    restart: always
  redis3:
    image: redis
    ports:
      - "6001:6379"
    restart: always
